version: "3.9"

services:
  database:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=cloud-file-storage
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  keycloak:
    image: quay.io/keycloak/keycloak
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=root
      - KEYCLOAK_ADMIN_PASSWORD=root
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://database:5432/cloud-file-storage
      - KC_DB_USERNAME=user
      - KC_DB_PASSWORD=password
    depends_on:
      - database
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/keycloak/realm/realm.json:/opt/keycloak/data/import/realm-export.json