version: "3.9"

services:
  cloud-file-storage-app:
    image: krios2146/cloud-file-storage
    ports:
      - "8082:8080"
    environment:
      - SPRING_DB_USER=spring
      - SPRING_DB_PASSWORD=P*6L9et0LwruZiT-Fe0aF*0RuG5GUv
      - SPRING_DB_URL=jdbc:postgresql://database:5432/cloud-file-storage
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - MINIO_CLIENT_ENDPOINT=http://78.153.130.215:9000
      - MINIO_CLIENT_USER=root
      - MINIO_CLIENT_PASSWORD=qa5ubrazi8r4m8zesp_crLj2b7sodl
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
  
  database:
    image: postgres:latest
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=cloud-file-storage
      - POSTGRES_USER=spring
      - POSTGRES_PASSWORD=P*6L9et0LwruZiT-Fe0aF*0RuG5GUv
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - ~/data/redis:/var/lib/redis
      - ~/data/redis/config:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    volumes:
      - ~/data/minio:/data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=qa5ubrazi8r4m8zesp_crLj2b7sodl
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://78.153.130.215:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3