version: "3.9"

services:
  database:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=cloud-file-storage
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  keycloak:
    image: quay.io/keycloak/keycloak
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=root
      - KEYCLOAK_ADMIN_PASSWORD=root
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://database:5432/cloud-file-storage
      - KC_DB_USERNAME=user
      - KC_DB_PASSWORD=password
    depends_on:
      - database
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/keycloak/realm/realm.json:/opt/keycloak/data/import/realm-export.json
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_IDENTITY_OPENID_CONFIG_URL=http://localhost:8080/realms/cloud-file-storage/.well-known/openid-configuration
      - MINIO_IDENTITY_OPENID_CLAIM_USERINFO=http://localhost:8080/realms/cloud-file-storage/protocol/openid-connect/userinfo
      - MINIO_IDENTITY_OPENID_VENDOR=keycloak
      - MINIO_IDENTITY_OPENID_KEYCLOAK_REALM=cloud-file-storage
      - MINIO_IDENTITY_OPENID_KEYCLOAK_ADMIN_URL=http://localhost:8080/admin/
    ports:
      - "9000:9000"
      - "9001:9001"